spring:
  application:
    name: customer
  profiles:
    active:
      - jdbc
      - default
  config:
    import: "optional:configserver:http://ANHNT:ANHNT-PASS@localhost:7000/configuration/config"
#  cloud:
#    config:
#      fail-fast: true
#      retry: