logging:
  level:
    root: INFO
    io.eventuate.tram: DEBUG

spring:
  application:
    name: customer
  profiles:
    active:
      - jdbc
      - default
  config:
    import: "optional:configserver:http://localhost:7000/configuration/config"

#    username: user
#    password: secret
#  cloud:
#    config:
#      fail-fast: true
#      retry: